# name: Notify Telegram on Release

# on:
#   release:
#     types: [published]

# jobs:
#   notify-telegram:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send message to Telegram
#         env:
#           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#           TELEGRAM_TOPIC_NEWS: ${{ secrets.TELEGRAM_TOPIC_NEWS }}
#           TELEGRAM_TOPIC_GENREAL: ${{ secrets.TELEGRAM_TOPIC_GENREAL }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#           RELEASE_TAG: ${{ github.event.release.tag_name }}
#           RELEASE_URL: ${{ github.event.release.html_url }}
#           RELEASE_NAME: ${{ github.event.release.name }}
#         run: |
#           curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
#             -d chat_id=$TELEGRAM_CHAT_ID \
#             -d text="🚀 Nova release publicada: *${RELEASE_NAME}* \n\n🔖 Tag: \`${RELEASE_TAG}\`\n📦 Veja em: $RELEASE_URL" \
#             -d parse_mode=Markdown -d message_thread_id=$TELEGRAM_TOPIC_GENREAL

#           curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
#             -d chat_id=$TELEGRAM_CHAT_ID \
#             -d text="🚀 Nova release publicada: *${RELEASE_NAME}* \n\n🔖 Tag: \`${RELEASE_TAG}\`\n📦 Veja em: $RELEASE_URL" \
#             -d parse_mode=Markdown -d message_thread_id=$TELEGRAM_TOPIC_NEWS
